// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero/index.svelte';
import Image from './Image/index.svelte';
import ImageCards from './ImageCards/index.svelte';
import MagicalSlice from './MagicalSlice/index.svelte';
import Quote from './Quote/index.svelte';
import Text from './Text/index.svelte';
import TextWithImage from './TextWithImage/index.svelte';

export const components = {
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	magical_slice: MagicalSlice,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage
};
